name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            artifact_name: gemini-nodeguard-linux-amd64
          - os: linux
            arch: arm64
            artifact_name: gemini-nodeguard-linux-arm64
          - os: linux
            arch: amd64
            artifact_name: gemini-nodeguard-linux-musl-amd64
          - os: darwin
            arch: amd64
            artifact_name: gemini-nodeguard-darwin-amd64
          - os: darwin
            arch: arm64
            artifact_name: gemini-nodeguard-darwin-arm64
          - os: windows
            arch: amd64
            artifact_name: gemini-nodeguard-windows-amd64.exe
          - os: windows
            arch: arm64
            artifact_name: gemini-nodeguard-windows-arm64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          cache: false

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl

      - name: Compile
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -o dist/${{ matrix.artifact_name }} ./cmd/checker

      - name: Optimize with UPX (Linux & Windows)
        if: matrix.os == 'linux' || matrix.os == 'windows'
        run: |
          upx --best --lzma dist/${{ matrix.artifact_name }}

      - name: Compress artifacts (Unix)
        if: matrix.os != 'windows'
        run: |
          cd dist
          tar -czvf ${{ matrix.artifact_name }}.tar.gz ${{ matrix.artifact_name }}
          rm ${{ matrix.artifact_name }}

      - name: Compress artifacts (Windows)
        if: matrix.os == 'windows'
        run: |
          cd dist
          zip ${{ matrix.artifact_name }}.zip ${{ matrix.artifact_name }}
          rm ${{ matrix.artifact_name }}

      - name: Publish Artifacts to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
